// <auto-generated />
using System;
using InterceptorSystem.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterceptorSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326194000_ModifyTags")]
    partial class ModifyTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Auth.Aggregates.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailPendente")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TelefoneVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasFilter("\"Telefone\" IS NOT NULL");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Auth.Aggregates.TokenVerificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DadosAdicionais")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("ContaId", "Tipo", "Usado");

                    b.ToTable("TokensVerificacao", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Alocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("interval");

                    b.Property<bool>("PermiteDobrarEscala")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEscala")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PostoId");

                    b.ToTable("Alocacoes", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<TimeOnly>("HorarioTrocaTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(6, 0, 0));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("QuantidadeIdealPorTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Nome");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MargemCoberturaFaltasPercentual")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("MargemLucroPercentual")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("NumeroDePostos")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentualAdicionalNoturno")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PercentualEncargosProvisoes")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ValorBeneficiosExtrasMensal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorDiariaCobrada")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ValorDiariaVigilante")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotalMensal")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ClienteId", "Status");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.ContratoTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TagId");

                    b.HasIndex("ContratoId", "TagId")
                        .IsUnique();

                    b.ToTable("ContratoTags", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Diaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlocacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusDiaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDiaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlocacaoId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Diarias", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("StatusFuncionario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoEscala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoFuncionario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.FuncionarioTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TagId");

                    b.HasIndex("FuncionarioId", "TagId")
                        .IsUnique();

                    b.ToTable("FuncionarioTags", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Posto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Postos", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nome")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Whatsapp.Aggregates.SessaoWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteIdSelecionado")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataSelecionada")
                        .HasColumnType("date");

                    b.Property<Guid?>("DiariaIdParaSubstituir")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FuncionarioSubstitutoId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpcoesCacheJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("PostoIdSelecionado")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UltimaAtividade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("SessoesWhatsapp", (string)null);
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Auth.Aggregates.Conta", b =>
                {
                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("ContaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Auth.Aggregates.TokenVerificacao", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Auth.Aggregates.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Alocacao", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", "Contrato")
                        .WithMany("Alocacoes")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Posto", "Posto")
                        .WithMany("Alocacoes")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Posto");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", b =>
                {
                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Email", "EmailGestor", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("EmailGestor");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Telefone", "TelefoneEmergencia", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("TelefoneEmergencia");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("EmailGestor");

                    b.Navigation("TelefoneEmergencia");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", "Cliente")
                        .WithMany("Contratos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.ContratoTag", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", "Contrato")
                        .WithMany("Tags")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Diaria", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Alocacao", "Alocacao")
                        .WithMany("Diarias")
                        .HasForeignKey("AlocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Funcionario", "Funcionario")
                        .WithMany("Diarias")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alocacao");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Funcionario", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", "Cliente")
                        .WithMany("Funcionarios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", "Contrato")
                        .WithMany("Funcionarios")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Telefone", "Celular", b1 =>
                        {
                            b1.Property<Guid>("FuncionarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("Celular");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("Funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("FuncionarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("Cpf");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("Funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.Navigation("Celular")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Contrato");

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.FuncionarioTag", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Funcionario", "Funcionario")
                        .WithMany("Tags")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Posto", b =>
                {
                    b.HasOne("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", "Cliente")
                        .WithMany("Postos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InterceptorSystem.Domain.SharedKernel.ValueObjects.Cep", "Cep", b1 =>
                        {
                            b1.Property<Guid>("PostoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("Cep");

                            b1.HasKey("PostoId");

                            b1.ToTable("Postos");

                            b1.WithOwner()
                                .HasForeignKey("PostoId");
                        });

                    b.Navigation("Cep")
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Alocacao", b =>
                {
                    b.Navigation("Diarias");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Cliente", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Funcionarios");

                    b.Navigation("Postos");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Contrato", b =>
                {
                    b.Navigation("Alocacoes");

                    b.Navigation("Funcionarios");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Funcionario", b =>
                {
                    b.Navigation("Diarias");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("InterceptorSystem.Domain.BoundedContexts.Operacoes.Aggregates.Posto", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
